admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /{_locale}/administration

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /{_locale}/administration
