index:
  path: /{_locale}/{page}
  controller: App\Controller\BlogController::list
  defaults:
    _locale: ka
    page: 1
  requirements:
    _locale:  ka|en
    page: \d+

single_blog:
  path: /{_locale}/blog/{id}
  controller: App\Controller\BlogController::single
  defaults:
    _locale: ka
    page: 1
  requirements:
    _locale:  ka|en
    page: \d+

about:
  path: /{_locale}/about
  controller: App\Controller\DefaultController::about
  defaults:
    _locale: ka
  requirements:
    _locale:  ka|en

sign_up:
  path: /{_locale}/register
  controller: App\Controller\AuthController::register
  defaults:
    _locale: ka
  requirements:
    _locale:  ka|en

sign_in:
  path: /{_locale}/login
  controller: App\Controller\AuthController::login
  defaults:
    _locale: ka
  requirements:
    _locale:  ka|en

app_logout:
  path: /logout
  methods: GET

verify_account:
  path: /{_locale}/verify/{token}
  controller: App\Controller\AuthController::verify
  defaults:
    _locale: ka
  requirements:
    _locale:  ka|en

reset_password:
  path: /{_locale}/reset-password
  controller: App\Controller\AuthController::resetPassword
  defaults:
    _locale: ka
  requirements:
    _locale:  ka|en

password_reset:
  path: /{_locale}/reset-password/{token}
  controller: App\Controller\AuthController::reset
  defaults:
    _locale: ka
  requirements:
    _locale:  ka|en

# compiler
compiler:
  path: /{_locale}/compiler
  controller: App\Controller\DefaultController::compiler
  defaults:
    _locale: ka
  requirements:
    _locale:  ka|en

compiler_compile:
  path: /api/compiler/compile
  controller: App\Controller\ApiController::compilerCompileCode
  methods: post

# Material
material_index:
  path: /{_locale}/material
  controller: App\Controller\MaterialController::index
  defaults:
    _locale: ka
  requirements:
    _locale:  ka|en

material_problems:
  path: /{_locale}/material/problems
  controller: App\Controller\MaterialController::problemsList
  defaults:
    _locale: ka
  requirements:
    _locale:  ka|en

material_single_problem:
  path: /{_locale}/material/problem/{id}
  controller: App\Controller\MaterialController::singleProblem
  defaults:
    _locale: ka
  requirements:
    _locale:  ka|en
    id: \d+

material_algorithms:
  path: /{_locale}/material/algorithms
  controller: App\Controller\MaterialController::algorithmsList
  defaults:
    _locale: ka
  requirements:
    _locale:  ka|en

# User
user_profile:
  path: /{_locale}/user/{username}
  controller: App\Controller\UserController::profile
  defaults:
    _locale: ka
  requirements:
    _locale:  ka|en

edit_profile:
  path: /{_locale}/edit-profile
  controller: App\Controller\UserController::edit
  defaults:
    _locale: ka
  requirements:
    _locale:  ka|en

# Problem
problem_list:
  path: /{_locale}/problems
  controller: App\Controller\ProblemController::list
  defaults:
    _locale: ka
  requirements:
    _locale:  ka|en

single_problem:
  path: /{_locale}/problem/{id}
  controller: App\Controller\ProblemController::single
  defaults:
    _locale: ka
  requirements:
    _locale:  ka|en
    id: \d+

solve_problem:
  path: /{_locale}/problem/{id}/solve
  controller: App\Controller\ProblemController::solve
  defaults:
    _locale: ka
  requirements:
    _locale:  ka|en
    id: \d+

submit_problem_solution:
  path: /api/compiler/submit-solution/{id}
  controller: App\Controller\ApiController::submitProblemSolution
  methods: post

solutions_status:
  path: /{_locale}/status
  controller: App\Controller\ProblemController::status
  defaults:
    _locale: ka
  requirements:
    _locale:  ka|en
    id: \d+